### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by eightfive1** [didi/LogiAM#16]
打包失败 少个依赖
![image](https://user-images.githubusercontent.com/31918921/149896197-31276c2a-6f26-4063-89c0-bb0d867beeff.png)

**Comment by huqidong** [comment]
你好，请在agent-manager工程编译、打包前，先对 system-metrcis 工程进行编译、打包（PS：在system-metrcis工程目录下执行命令 mvn clean install -DskipTests）
