### ISSUE TITLE
swan-agent在centos7打包报错

### ISSUE THREAD

**Issue by zhbdesign** [didi/LogIAM#2]
![image](https://user-images.githubusercontent.com/50901800/124694971-dae96180-df14-11eb-9adc-4eabbc52ddb6.png)

**Comment by zhangliangboy** [comment]
是自己环境和打包问题吗？

**Comment by zhbdesign** [comment]
> 是自己环境和打包问题吗？

打包试了下没有问题了，但是swan-agent启动有问题
![image](https://user-images.githubusercontent.com/50901800/124699827-2ce2b500-df1e-11eb-9905-1d7df0071800.png)

**Comment by zhbdesign** [comment]
> 是自己环境和打包问题吗？

agent依赖manage，必须先打包manage

**Comment by zhbdesign** [comment]
先启动manage，agent配置manage的IP和port，注册到manage
