### ISSUE TITLE
日志文件是先Gzip 压缩，再Base64 编码的，这种在agent侧可以进行解码解压缩处理吗

### ISSUE THREAD

**Issue by zhbdesign** [didi/LogiAM#3]
日志文件是先Gzip 压缩，再Base64 编码的，这种在agent侧可以进行解码解压缩处理吗

**Comment by zhangliangboy** [comment]
可以在Read侧自己拓展实现，默认我们不支持，这种场景比较小众，也可以在消费侧自己ETL转换

**Comment by zhangliangboy** [comment]
没有计划支持，用户可以拓展功能实现
