### ISSUE TITLE
有提供agent 源码或者安装程序吗？

### ISSUE THREAD

**Issue by melin** [didi/LogiAM#4]
有提供agent 源码或者安装程序吗？只开源管理管理工具？

**Comment by zhangliangboy** [comment]
包含Agent源码和管理工具，具体你下载代码你就看得出来

**Comment by huqidong** [comment]
Agent 源码有的：https://github.com/didi/LogiAM/tree/master/log-agent

**Comment by melin** [comment]
> Agent 源码有的：https://github.com/didi/LogiAM/tree/master/log-agent
以为是一个c++或者go 写的agent，java agent 资源怎么样？ 有这方面介绍吗？以前做过基于filebeat 改造的agent，统一采集平台

**Comment by huqidong** [comment]
内存、cpu消耗较go开发的filebeat略大，但在一个数量级上，后续我们会基于一些典型场景给出一个 “性能 - 资源消耗” benchmark.我们agent拥有每秒100MB+的采集性能，这点是包括filebeat在内的开源agent所不具备的.
