### ISSUE TITLE
manager 和angent 配置maven-compiler-plugin 编译jdk 版本不一致

### ISSUE THREAD

**Issue by melin** [didi/LogiAM#6]
manager 和angent 配置maven-compiler-plugin 编译jdk 版本不一致，不知道为什么有这样差异，angent-client 必须jdk11？现在还在用jdk8
manger 1.8
angent 11

发现kafka-client 版本也不一致，集群部署的是2.8，可以升级到2.8？
manager 2.7
angent 2.3

**Comment by huqidong** [comment]
请更新一下代码.
