### ISSUE TITLE
集群地址不支持填写多过？

### ISSUE THREAD

**Issue by melin** [didi/LogiAM#8]
不支持填写多个地址，生产端初始化属性能否换行分隔，一行一个属性，现在逗号分隔，全部挤在一起，很不友好。
![image](https://user-images.githubusercontent.com/1145830/132639596-8f867109-bb77-4146-93f3-56a374060267.png)

**Comment by huqidong** [comment]
谢谢你宝贵的建议，我们会优化相应界面配置，敬请关注

**Comment by melin** [comment]
> 谢谢你宝贵的建议，我们会优化相应界面配置，敬请关注

方便把你微信告诉我吗？ 可以发邮箱：libinsong1204 # gmail.com

**Comment by melin** [comment]
这个问题解决？

**Comment by huqidong** [comment]
集群地址不支持填写多个 -- 请更新一下代码
生产端初始化属性能否换行分隔，一行一个属性，现在逗号分隔，全部挤在一起，很不友好 --感谢宝贵的建议，这个问题，我们已提上产品优化议程，敬请关注
